extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  DefaultReviewCond: &DefaultReviewCond
    - "#approved-reviews-by>=1"
    - author=dependabot[bot]
    - author=mergify-ci-bot
queue_rules:
  - name: default
    <<: *DefaultQueueOptions
    queue_conditions:
      - base=main
      - -author=dependabot[bot]
    merge_conditions: []

  - name: lowprio
    <<: *DefaultQueueOptions
    queue_conditions:
      - "#commits=1"
      - author=dependabot[bot]
    merge_method: fast-forward
    merge_conditions: []
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - label!=manual merge
    actions:
      queue:

  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

merge_protections:
  - name: 👀 Review Requirements
    if: []
    success_conditions:
      - or: *DefaultReviewCond

merge_queue:
  max_parallel_checks: 5

merge_protections_settings:
  reporting_method: deployments
  auto_merge_conditions: true
