name: 'add-linear-author-as-reviewer'
description: 'Add Linear author as reviewer'
author: 'Mergify'
branding:
  icon: 'at-sign'
  color: 'blue'
inputs:
  LINEAR_API_KEY:
    required: true
    description: 'Linear Api Key'
  GITHUB_TOKEN:
    required: true
    description: 'GitHub Token'
  DEFAULT_REVIEWER:
    required: false
    description: 'Default GH reviewer if no Linear author found'
    default: ''
  EMAIL_MAPPING:
    required: true
    description: 'Linear Email to GitHub login mapping (one by line and separated by a space)'
  LINEAR_ISSUE_REGEX:
    required: false
    description: 'Linear issue regex to find the issue ID'
    default: 'MRGFY-\d+'
runs:
  using: 'composite'
  steps:
    - id: extract
      shell: bash
      run: |
        python3 -m venv venv
        venv/bin/pip install -r ${{ github.action_path }}/requirements.txt
        venv/bin/python ${{ github.action_path }}/linear-extract-reviewers.py >> $GITHUB_OUTPUT
      env:
        INPUT_LINEAR_API_KEY: ${{ inputs.LINEAR_API_KEY }}
        INPUT_LINEAR_ISSUE_REGEX: ${{ inputs.LINEAR_ISSUE_REGEX }}
        INPUT_DEFAULT_REVIEWER: ${{ inputs.DEFAULT_REVIEWER }}
        INPUT_EMAIL_MAPPING: ${{ inputs.EMAIL_MAPPING }}
        INPUT_PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
        INPUT_PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
    - shell: bash
      if: "${{ steps.extract.outputs.creators }}"
      run: |
        set -x
        # Split creators string by commas and process each reviewer
        creators="${{steps.extract.outputs.creators}}"
        IFS=',' read -ra reviewers <<< "$creators"
        for reviewer in "${reviewers[@]}"; do
          # Trim whitespace
          reviewer=$(echo "${reviewer}" | xargs)
          (gh pr view ${{github.event.pull_request.html_url}} --json latestReviews | jq -e '.latestReviews[] | select(.author.login == "'${reviewer}'" and .state != "DISMISSED" and .state != "COMMENTED")' && \
          echo "Review of ${reviewer} has already been requested") \
          || \
          (gh pr edit ${{github.event.pull_request.html_url}} --add-reviewer ${reviewer} && \
          echo "Requested user review from ${reviewer} via 'gh' CLI") \
          || \
          echo "Failed to request review from ${reviewer}"
        done
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
