name: 'add-linear-author-as-reviewer'
description: 'Add Linear author as reviewer'
author: 'Mergify'
inputs:
  LINEAR_API_KEY:
    required: true
    description: 'Linear Api Key'
  GITHUB_TOKEN:
    required: true
    description: 'GitHub Token'
  EMAIL_MAPPING:
    required: true
    description: 'Linear Email to GitHub login mapping (one by line and separated by a space)'
runs:
  using: 'composite'
  steps:
    - id: extract
      shell: bash
      run: |
        python3 -m venv venv
        venv/bin/pip install httpx
        venv/bin/python ${{ github.action_path }}/linear-extract-reviewers.py
      env:
        INPUT_LINEAR_API_KEY: ${{ inputs.LINEAR_API_KEY }}
        INPUT_EMAIL_MAPPING: ${{ inputs.EMAIL_MAPPING }}
        INPUT_PULL_REQUEST_BODY: ${{ github.event.pull_request.body  }}
    - shell: bash
      if: "${{ steps.extract.outputs.creators }}"
      run: |
        set -x
        for creator in ${{steps.extract.outputs.creators}}; do
          gh pr view ${{github.event.pull_request.html_url}} --json latestReviews |jq -e '.latestReviews[] | select(.author.login == "'${creator}'" and .state != "DISMISSED")' \
          && \
            echo "Review of ${creator} has already been requested" \
          || \
            curl -X POST \
                -H "Content-type: application/json" \
                -H "Accept: application/json" \
                -H "Authorization: token $GITHUB_TOKEN" \
                -d '{"reviewers": ["'${creator}'"]}' \
                ${{github.event.pull_request.url}}/requested_reviewers
            # This doesn't work because of https://github.com/cli/cli/issues/4844
            # gh pr edit ${{github.event.pull_request.html_url}} --add-reviewer $creator
        done
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
